/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.5 Mon Mar 31 14:40:44 2025.
 */

#include <string.h>

#include "can_wheelchair.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int can_wheelchair_id_100_consigne_pack(
    uint8_t *dst_p,
    const struct can_wheelchair_id_100_consigne_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->cons_can_axe_x, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->cons_can_axe_y, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->activation_cons_can_axe_y, 1u, 0x02u);
    dst_p[2] |= pack_left_shift_u8(src_p->activation_cons_can_axe_x, 0u, 0x01u);

    return (8);
}

int can_wheelchair_id_100_consigne_unpack(
    struct can_wheelchair_id_100_consigne_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cons_can_axe_x = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->cons_can_axe_y = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->activation_cons_can_axe_y = unpack_right_shift_u8(src_p[2], 1u, 0x02u);
    dst_p->activation_cons_can_axe_x = unpack_right_shift_u8(src_p[2], 0u, 0x01u);

    return (0);
}

int can_wheelchair_id_100_consigne_init(struct can_wheelchair_id_100_consigne_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_wheelchair_id_100_consigne_t));

    return 0;
}

uint8_t can_wheelchair_id_100_consigne_cons_can_axe_x_encode(double value)
{
    return (uint8_t)(value - -100.0);
}

double can_wheelchair_id_100_consigne_cons_can_axe_x_decode(uint8_t value)
{
    return ((double)value + -100.0);
}

bool can_wheelchair_id_100_consigne_cons_can_axe_x_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_wheelchair_id_100_consigne_cons_can_axe_y_encode(double value)
{
    return (uint8_t)(value - -100.0);
}

double can_wheelchair_id_100_consigne_cons_can_axe_y_decode(uint8_t value)
{
    return ((double)value + -100.0);
}

bool can_wheelchair_id_100_consigne_cons_can_axe_y_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_wheelchair_id_100_consigne_activation_cons_can_axe_y_encode(double value)
{
    return (uint8_t)(value);
}

double can_wheelchair_id_100_consigne_activation_cons_can_axe_y_decode(uint8_t value)
{
    return ((double)value);
}

bool can_wheelchair_id_100_consigne_activation_cons_can_axe_y_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_wheelchair_id_100_consigne_activation_cons_can_axe_x_encode(double value)
{
    return (uint8_t)(value);
}

double can_wheelchair_id_100_consigne_activation_cons_can_axe_x_decode(uint8_t value)
{
    return ((double)value);
}

bool can_wheelchair_id_100_consigne_activation_cons_can_axe_x_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int can_wheelchair_id_110_diag_pack(
    uint8_t *dst_p,
    const struct can_wheelchair_id_110_diag_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->position_joystick_y, 4u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->position_joystick_y, 4u, 0xf0u);
    dst_p[1] |= pack_right_shift_u16(src_p->position_joystick_x, 8u, 0x0fu);
    dst_p[2] |= pack_left_shift_u16(src_p->position_joystick_x, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->id100_trame_valide, 7u, 0x80u);
    dst_p[3] |= pack_left_shift_u8(src_p->cons_x_robot, 6u, 0x40u);
    dst_p[3] |= pack_left_shift_u8(src_p->cons_y_robot, 5u, 0x20u);
    dst_p[3] |= pack_right_shift_u16(src_p->mesure_tension_24_v, 7u, 0x1fu);
    dst_p[4] |= pack_left_shift_u16(src_p->mesure_tension_24_v, 1u, 0xfeu);
    dst_p[4] |= pack_right_shift_u16(src_p->mesure_tension_12_v, 11u, 0x01u);
    dst_p[5] |= pack_right_shift_u16(src_p->mesure_tension_12_v, 3u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->mesure_tension_12_v, 5u, 0xe0u);
    dst_p[6] |= pack_right_shift_u16(src_p->mesure_tension_19_v, 7u, 0x1fu);
    dst_p[7] |= pack_left_shift_u16(src_p->mesure_tension_19_v, 1u, 0xfeu);
    dst_p[7] |= pack_left_shift_u8(src_p->desactivation_robot_timeout_can, 0u, 0x01u);

    return (8);
}

int can_wheelchair_id_110_diag_unpack(
    struct can_wheelchair_id_110_diag_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->position_joystick_y = unpack_left_shift_u16(src_p[0], 4u, 0xffu);
    dst_p->position_joystick_y |= unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    dst_p->position_joystick_x = unpack_left_shift_u16(src_p[1], 8u, 0x0fu);
    dst_p->position_joystick_x |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->id100_trame_valide = unpack_right_shift_u8(src_p[3], 7u, 0x80u);
    dst_p->cons_x_robot = unpack_right_shift_u8(src_p[3], 6u, 0x40u);
    dst_p->cons_y_robot = unpack_right_shift_u8(src_p[3], 5u, 0x20u);
    dst_p->mesure_tension_24_v = unpack_left_shift_u16(src_p[3], 7u, 0x1fu);
    dst_p->mesure_tension_24_v |= unpack_right_shift_u16(src_p[4], 1u, 0xfeu);
    dst_p->mesure_tension_12_v = unpack_left_shift_u16(src_p[4], 11u, 0x01u);
    dst_p->mesure_tension_12_v |= unpack_left_shift_u16(src_p[5], 3u, 0xffu);
    dst_p->mesure_tension_12_v |= unpack_right_shift_u16(src_p[6], 5u, 0xe0u);
    dst_p->mesure_tension_19_v = unpack_left_shift_u16(src_p[6], 7u, 0x1fu);
    dst_p->mesure_tension_19_v |= unpack_right_shift_u16(src_p[7], 1u, 0xfeu);
    dst_p->desactivation_robot_timeout_can = unpack_right_shift_u8(src_p[7], 0u, 0x01u);

    return (0);
}

int can_wheelchair_id_110_diag_init(struct can_wheelchair_id_110_diag_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_wheelchair_id_110_diag_t));

    return 0;
}

uint16_t can_wheelchair_id_110_diag_position_joystick_y_encode(double value)
{
    return (uint16_t)(value);
}

double can_wheelchair_id_110_diag_position_joystick_y_decode(uint16_t value)
{
    return ((double)value);
}

bool can_wheelchair_id_110_diag_position_joystick_y_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t can_wheelchair_id_110_diag_position_joystick_x_encode(double value)
{
    return (uint16_t)(value);
}

double can_wheelchair_id_110_diag_position_joystick_x_decode(uint16_t value)
{
    return ((double)value);
}

bool can_wheelchair_id_110_diag_position_joystick_x_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint8_t can_wheelchair_id_110_diag_id100_trame_valide_encode(double value)
{
    return (uint8_t)(value);
}

double can_wheelchair_id_110_diag_id100_trame_valide_decode(uint8_t value)
{
    return ((double)value);
}

bool can_wheelchair_id_110_diag_id100_trame_valide_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_wheelchair_id_110_diag_cons_x_robot_encode(double value)
{
    return (uint8_t)(value);
}

double can_wheelchair_id_110_diag_cons_x_robot_decode(uint8_t value)
{
    return ((double)value);
}

bool can_wheelchair_id_110_diag_cons_x_robot_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_wheelchair_id_110_diag_cons_y_robot_encode(double value)
{
    return (uint8_t)(value);
}

double can_wheelchair_id_110_diag_cons_y_robot_decode(uint8_t value)
{
    return ((double)value);
}

bool can_wheelchair_id_110_diag_cons_y_robot_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t can_wheelchair_id_110_diag_mesure_tension_24_v_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double can_wheelchair_id_110_diag_mesure_tension_24_v_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool can_wheelchair_id_110_diag_mesure_tension_24_v_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t can_wheelchair_id_110_diag_mesure_tension_12_v_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double can_wheelchair_id_110_diag_mesure_tension_12_v_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool can_wheelchair_id_110_diag_mesure_tension_12_v_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t can_wheelchair_id_110_diag_mesure_tension_19_v_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double can_wheelchair_id_110_diag_mesure_tension_19_v_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool can_wheelchair_id_110_diag_mesure_tension_19_v_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint8_t can_wheelchair_id_110_diag_desactivation_robot_timeout_can_encode(double value)
{
    return (uint8_t)(value);
}

double can_wheelchair_id_110_diag_desactivation_robot_timeout_can_decode(uint8_t value)
{
    return ((double)value);
}

bool can_wheelchair_id_110_diag_desactivation_robot_timeout_can_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int can_wheelchair_id_111_diag_pack(
    uint8_t *dst_p,
    const struct can_wheelchair_id_111_diag_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->vitesse_roue_gauche, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->vitesse_roue_gauche, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->vitesse_roue_droite, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->vitesse_roue_droite, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->direction_roue_droite, 5u, 0x20u);
    dst_p[4] |= pack_left_shift_u8(src_p->direction_roue_gauche, 4u, 0x10u);
    dst_p[4] |= pack_left_shift_u8(src_p->dft_maxi_capteur_joystick_axe_y, 3u, 0x08u);
    dst_p[4] |= pack_left_shift_u8(src_p->dft_mini_capteur_joystick_axe_y, 2u, 0x04u);
    dst_p[4] |= pack_left_shift_u8(src_p->dft_maxi_capteur_joystick_axe_x, 1u, 0x02u);
    dst_p[4] |= pack_left_shift_u8(src_p->dft_mini_capteur_joystick_axe_x, 0u, 0x01u);

    return (8);
}

int can_wheelchair_id_111_diag_unpack(
    struct can_wheelchair_id_111_diag_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->vitesse_roue_gauche = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->vitesse_roue_gauche |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->vitesse_roue_droite = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->vitesse_roue_droite |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->direction_roue_droite = unpack_right_shift_u8(src_p[4], 5u, 0x20u);
    dst_p->direction_roue_gauche = unpack_right_shift_u8(src_p[4], 4u, 0x10u);
    dst_p->dft_maxi_capteur_joystick_axe_y = unpack_right_shift_u8(src_p[4], 3u, 0x08u);
    dst_p->dft_mini_capteur_joystick_axe_y = unpack_right_shift_u8(src_p[4], 2u, 0x04u);
    dst_p->dft_maxi_capteur_joystick_axe_x = unpack_right_shift_u8(src_p[4], 1u, 0x02u);
    dst_p->dft_mini_capteur_joystick_axe_x = unpack_right_shift_u8(src_p[4], 0u, 0x01u);

    return (0);
}

int can_wheelchair_id_111_diag_init(struct can_wheelchair_id_111_diag_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_wheelchair_id_111_diag_t));

    return 0;
}

uint16_t can_wheelchair_id_111_diag_vitesse_roue_gauche_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double can_wheelchair_id_111_diag_vitesse_roue_gauche_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool can_wheelchair_id_111_diag_vitesse_roue_gauche_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t can_wheelchair_id_111_diag_vitesse_roue_droite_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double can_wheelchair_id_111_diag_vitesse_roue_droite_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool can_wheelchair_id_111_diag_vitesse_roue_droite_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t can_wheelchair_id_111_diag_direction_roue_droite_encode(double value)
{
    return (uint8_t)(value);
}

double can_wheelchair_id_111_diag_direction_roue_droite_decode(uint8_t value)
{
    return ((double)value);
}

bool can_wheelchair_id_111_diag_direction_roue_droite_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_wheelchair_id_111_diag_direction_roue_gauche_encode(double value)
{
    return (uint8_t)(value);
}

double can_wheelchair_id_111_diag_direction_roue_gauche_decode(uint8_t value)
{
    return ((double)value);
}

bool can_wheelchair_id_111_diag_direction_roue_gauche_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_wheelchair_id_111_diag_dft_maxi_capteur_joystick_axe_y_encode(double value)
{
    return (uint8_t)(value);
}

double can_wheelchair_id_111_diag_dft_maxi_capteur_joystick_axe_y_decode(uint8_t value)
{
    return ((double)value);
}

bool can_wheelchair_id_111_diag_dft_maxi_capteur_joystick_axe_y_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_wheelchair_id_111_diag_dft_mini_capteur_joystick_axe_y_encode(double value)
{
    return (uint8_t)(value);
}

double can_wheelchair_id_111_diag_dft_mini_capteur_joystick_axe_y_decode(uint8_t value)
{
    return ((double)value);
}

bool can_wheelchair_id_111_diag_dft_mini_capteur_joystick_axe_y_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_wheelchair_id_111_diag_dft_maxi_capteur_joystick_axe_x_encode(double value)
{
    return (uint8_t)(value);
}

double can_wheelchair_id_111_diag_dft_maxi_capteur_joystick_axe_x_decode(uint8_t value)
{
    return ((double)value);
}

bool can_wheelchair_id_111_diag_dft_maxi_capteur_joystick_axe_x_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_wheelchair_id_111_diag_dft_mini_capteur_joystick_axe_x_encode(double value)
{
    return (uint8_t)(value);
}

double can_wheelchair_id_111_diag_dft_mini_capteur_joystick_axe_x_decode(uint8_t value)
{
    return ((double)value);
}

bool can_wheelchair_id_111_diag_dft_mini_capteur_joystick_axe_x_is_in_range(uint8_t value)
{
    return (value <= 1u);
}
